"""Add QuesrionModel and AnswerModel relationship link

Revision ID: 027a55351862
Revises: 7a12cddcefa8
Create Date: 2022-08-28 12:53:54.402844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027a55351862'
down_revision = '7a12cddcefa8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
