"""Change AnswerModel title no unique

Revision ID: 7a12cddcefa8
Revises: 272f6a4557e1
Create Date: 2022-08-27 23:17:24.420282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a12cddcefa8'
down_revision = '272f6a4557e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_title_key', 'answers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('answers_title_key', 'answers', ['title'])
    # ### end Alembic commands ###
